### ISSUE TITLE
La gestion des dépendances avec Python

### ISSUE THREAD

**Issue by nioperas06** [PythonBenin/workshops#1]
`Python 2`, `Python 3`, `Python 2.7`, `Python 3.5`, `Python 3.6` ... On s'y perdrait même avec les versions. Gérez la version de `Python` dans son projet mais aussi comment installer et connaître l'entièreté des pacquets `Python` installés est un vrai challenge. Tout développeur `Python` doit savoir le faire. 

Eh ben, qu'attendons-nous?

**Comment by OthnielDona** [comment]
Je suis un amoureux de `Python`, mais quand il s'agit de gérer les packets (modules) et leurs dépendances, je démissionne.
