### ISSUE TITLE
Google Challenge

### ISSUE THREAD

**Issue by OthnielDona** [PythonBenin/workshops#2]
Les challenges que propose Google tel que le **hash code** et le **code jam**, sont très bons pour travailler les algorithmes.

Résoudre ses challenges permettra
* au débutant d'apprendre `Python`,
* à ceux qui programme déjà en `Python` d'écrire des codes plus *pythonic*,
* a tout le monde de travailler leur *logic* et de penser de façon plus *algorithmique*,
* mais surtout le travail d'équipe.

**Comment by nioperas06** [comment]
@OthnielDona  tu pourras animer la session?

**Comment by nioperas06** [comment]
@OthnielDona  tu pourras animer la session?

**Comment by OthnielDona** [comment]
Je pourrai, oui. Mais j'aurais besoin de beaucoup d'aide. Je ne suis pas très expérimenté.

**Comment by nioperas06** [comment]
Hello @OthnielDona tu peux proposer une description et un sommaire de ce que tu voudrais faire, on peut le programmer dans une semaine. Exemple: https://github.com/parisjs/talks/issues/55

**Comment by OthnielDona** [comment]
Le premier challenge consistera a classe une collection de photos en slideshow. Les details se trouve dans [photo_slideshow.pdf](https://github.com/PythonBenin/workshops/files/3413380/photo_slideshow.pdf)

**Comment by nioperas06** [comment]
Du coup, ça veut dire que tu vas nous montrer comment tu résous le challenge?

**Comment by OthnielDona** [comment]
Nous allons le résoudre ensemble. Sa va être un travail d'équipe. J'ai une solution mais qui n'est pas parfait. Elle pourrait servir de point de départ vers une solution plus optimisé.

**Comment by nioperas06** [comment]
🤔 Alors là ce sera plutôt une séance physique, pas en ligne.

**Comment by OthnielDona** [comment]
Voyons ce qu'en pense les autres.
